# -*- coding: utf-8 -*-
"""ReportCell — 실험 결과 자동 리포팅.

분석 결과를 종합하여 Markdown 형식의 리포트를 자동으로 생성합니다.
반복적인 실험 결과를 체계적으로 기록하고, 연구 노트(Lab Note)로 활용합니다.
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any, Dict, List

import numpy as np
import pandas as pd

from engine.cells.base_cell import BaseCell
from engine.config import WhyLabConfig


class ReportCell(BaseCell):
    """분석 결과를 Markdown 리포트로 변환하는 셀.

    Args:
        config: WhyLab 전역 설정 객체.
    """

    def __init__(self, config: WhyLabConfig) -> None:
        super().__init__(name="report_cell", config=config)

    def execute(self, inputs: Dict[str, Any]) -> Dict[str, Any]:
        """분석 결과를 바탕으로 리포트를 생성합니다.

        Args:
            inputs: 이전 셀들의 모든 출력 (ATE, CATE, DataFrame 등).

        Returns:
            생성된 리포트 파일 경로.
        """
        self.logger.info("리포트 생성 시작")

        # 데이터 추출
        ate = inputs.get("ate", 0.0)
        ate_ci_lower = inputs.get("ate_ci_lower", 0.0)
        ate_ci_upper = inputs.get("ate_ci_upper", 0.0)
        cate_preds = inputs.get("cate_predictions", np.array([]))
        feature_names = inputs.get("feature_names", [])
        
        # 세그먼트 분석 결과 (ExportCell로직 재사용 또는 inputs에서 가져오기)
        # 여기서는 간단히 CATE 통계만 요약
        cate_mean = float(np.mean(cate_preds)) if len(cate_preds) > 0 else 0.0
        cate_std = float(np.std(cate_preds)) if len(cate_preds) > 0 else 0.0

        # 리포트 내용 생성
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        scenario_name = inputs.get("scenario_name", "Unknown Scenario") # Pipeline에서 주입 필요
        
        report_content = self._generate_markdown(
            timestamp=timestamp,
            scenario=scenario_name,
            ate=ate,
            ci=(ate_ci_lower, ate_ci_upper),
            cate_stats={"mean": cate_mean, "std": cate_std},
            features=feature_names,
            n_samples=len(inputs.get("dataframe", []))
        )

        # 파일 저장
        output_dir = self.config.paths.reports_dir
        output_dir.mkdir(parents=True, exist_ok=True)
        
        filename = f"experiment_report_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
        file_path = output_dir / filename
        
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(report_content)

        self.logger.info("리포트 저장 완료: %s", file_path)

        return {
            "report_path": str(file_path),
            "report_content": report_content
        }

    def _generate_markdown(
        self,
        timestamp: str,
        scenario: str,
        ate: float,
        ci: tuple,
        cate_stats: Dict[str, float],
        features: List[str],
        n_samples: int
    ) -> str:
        """Markdown 텍스트를 생성합니다."""
        
        is_significant = not (ci[0] <= 0 <= ci[1])
        significance_text = "**통계적으로 유의함**" if is_significant else "통계적으로 유의하지 않음"
        
        effect_direction = "증가" if ate > 0 else "감소"
        
        return f"""# 🧪 WhyLab Experiment Report

**Date**: {timestamp}
**Scenario**: {scenario}
**Samples**: {n_samples:,} samples
**Features**: {', '.join(features)}

---

## 1. Executive Summary

본 실험에서는 **{scenario}** 시나리오에 대한 인과 효과를 추정했습니다.
분석 결과, 처치(Treatment)는 결과 변수(Outcome)를 평균적으로 **{ate:.4f}** 만큼 **{effect_direction}**시키는 것으로 나타났습니다.
이 결과는 95% 신뢰구간 [{ci[0]:.4f}, {ci[1]:.4f}]을 고려할 때 {significance_text}입니다.

> **Key Finding**:
> ATE = {ate:.4f} (95% CI: {ci[0]:.4f} ~ {ci[1]:.4f})

---

## 2. Heterogeneity Analysis (CATE)

개별 처치 효과(CATE)의 분포를 분석하여 이질성(Heterogeneity) 존재 여부를 확인했습니다.

- **Mean CATE**: {cate_stats['mean']:.4f}
- **Std Dev**: {cate_stats['std']:.4f}

{"**💡 Insight**: CATE의 표준편차가 커서 사용자별로 효과 차이가 뚜렷합니다. 타겟팅 정책 최적화가 필요합니다." if cate_stats['std'] > 0.01 else "특별한 이질성이 관찰되지 않았습니다. 전체 유저에게 동일한 정책을 적용해도 무방합니다."}

---

## 3. Methodology Note

- **Model**: Double Machine Learning (DML)
- **Inference**: LinearDML / CausalForestDML
- **Cross-Validation**: 5-fold Cross-Fitting
- **Metric**: RMSE (Estimation), Coverage (Inference)

---

*Generated by WhyLab Engine*
"""
